-- ============================================================================
-- Journal Safe MVP - Seed Data Migration
-- ============================================================================
-- This migration populates the prompts and affirmations tables with
-- content for the eating disorder-safe wellness journaling app.
--
-- Data sources:
--   - content/prompts.json (100 journaling prompts)
--   - content/affirmations.json (50 affirmations)
--
-- Generated by: scripts/generate-seed-sql.js
-- Generated at: 2025-11-17T20:14:05.753Z
--
-- Note: This migration is idempotent - it will only insert data if the
-- tables are empty, so it's safe to run multiple times.
-- ============================================================================

-- ============================================================================
-- Insert prompts (100 total)
-- ============================================================================
INSERT INTO prompts (category, prompt_text)
SELECT * FROM (VALUES
  ('gratitude', 'What''s one small thing that brought you comfort today?'),
  ('gratitude', 'Who is someone in your life that makes you feel safe? What do they do that helps you feel this way?'),
  ('gratitude', 'What''s something in nature that you appreciate today?'),
  ('gratitude', 'Describe a moment today when you felt present, even if it was brief.'),
  ('gratitude', 'What''s a simple pleasure you''re grateful for right now?'),
  ('gratitude', 'What sound, smell, or sensation brought you peace today?'),
  ('gratitude', 'What''s something kind that someone did for you recently?'),
  ('gratitude', 'What part of your living space makes you feel most at ease?'),
  ('gratitude', 'What''s a resource or support that you''re grateful to have access to?'),
  ('gratitude', 'What ability or strength of yours are you appreciating today?'),
  ('gratitude', 'What creative outlet or hobby brings you joy?'),
  ('gratitude', 'What''s something about this season or time of year that you enjoy?'),
  ('gratitude', 'Who or what made you smile recently?'),
  ('gratitude', 'What''s a piece of art, music, or writing that you''re grateful exists?'),
  ('gratitude', 'What''s something you''re looking forward to, no matter how small?'),
  ('gratitude', 'What''s a comfort item or object that brings you a sense of safety?'),
  ('gratitude', 'What''s something about your body that you appreciate for what it allows you to do or experience?'),
  ('gratitude', 'What''s a memory that brings you warmth when you think about it?'),
  ('gratitude', 'What opportunity for rest or restoration are you grateful for today?'),
  ('gratitude', 'What''s something that exists in your life now that didn''t a year ago?'),
  ('self-compassion', 'If a dear friend was feeling what you''re feeling right now, what would you say to them?'),
  ('self-compassion', 'What does your inner critic say to you? Can you respond with gentleness instead?'),
  ('self-compassion', 'What''s one way you can be gentle with yourself today?'),
  ('self-compassion', 'What permission do you need to give yourself right now?'),
  ('self-compassion', 'What would unconditional kindness toward yourself look like today?'),
  ('self-compassion', 'What''s something difficult you''re going through that deserves acknowledgment?'),
  ('self-compassion', 'How can you honor your needs today without judgment?'),
  ('self-compassion', 'What would it feel like to accept where you are right now in your journey?'),
  ('self-compassion', 'What''s one harsh expectation you can release today?'),
  ('self-compassion', 'What does rest mean to you, and how can you give yourself that today?'),
  ('self-compassion', 'What''s something you''ve been criticizing yourself for that you can choose to be curious about instead?'),
  ('self-compassion', 'How can you speak to yourself with the same compassion you''d offer a child?'),
  ('self-compassion', 'What boundary do you need to set to protect your peace?'),
  ('self-compassion', 'What''s one way your body is asking for care today?'),
  ('self-compassion', 'What would self-care look like for you right now, free from shoulds or expectations?'),
  ('self-compassion', 'What parts of yourself have you been rejecting that deserve acceptance?'),
  ('self-compassion', 'How can you give yourself credit for simply showing up today?'),
  ('self-compassion', 'What''s a mistake or ''failure'' you can reframe as a learning experience?'),
  ('self-compassion', 'What would happen if you gave yourself permission to not be okay right now?'),
  ('self-compassion', 'What''s one small act of kindness you can offer yourself today?'),
  ('self-compassion', 'How can you be patient with your healing process today?'),
  ('self-compassion', 'What would it feel like to treat yourself as someone worthy of care?'),
  ('self-compassion', 'What''s something you need to hear right now that no one else can say to you?'),
  ('self-compassion', 'How can you make space for both your struggles and your strength today?'),
  ('self-compassion', 'What''s one way you can prioritize your wellbeing without guilt?'),
  ('emotional-reflection', 'What emotion is most present for you today, and where do you feel it in your body?'),
  ('emotional-reflection', 'What''s underneath the surface of what you''re feeling right now?'),
  ('emotional-reflection', 'What need might your emotions be trying to communicate to you?'),
  ('emotional-reflection', 'When did you first notice this feeling today? What was happening?'),
  ('emotional-reflection', 'What''s a difficult emotion you''ve been avoiding, and what might it be trying to tell you?'),
  ('emotional-reflection', 'How do you know when you''re feeling overwhelmed, and what are your early warning signs?'),
  ('emotional-reflection', 'What emotions feel safe for you to express, and which ones don''t?'),
  ('emotional-reflection', 'What''s bringing you the most peace or anxiety right now?'),
  ('emotional-reflection', 'Describe your emotional landscape today. What weather pattern would it be?'),
  ('emotional-reflection', 'What feeling are you carrying from yesterday that you haven''t processed yet?'),
  ('emotional-reflection', 'What makes you feel most alive and present?'),
  ('emotional-reflection', 'What emotion surprised you today, and why do you think it showed up?'),
  ('emotional-reflection', 'How are you really doing beneath the ''I''m fine''?'),
  ('emotional-reflection', 'What feeling would you like to experience more of in your life?'),
  ('emotional-reflection', 'What does joy look like for you, even in small moments?'),
  ('emotional-reflection', 'What''s taking up the most emotional space for you right now?'),
  ('emotional-reflection', 'When do you feel most like yourself?'),
  ('emotional-reflection', 'What emotion are you most comfortable with, and why might that be?'),
  ('emotional-reflection', 'What feelings came up for you in connection today?'),
  ('emotional-reflection', 'What''s one emotion you wish you could better understand about yourself?'),
  ('progress-growth', 'What''s something you understand about yourself now that you didn''t before?'),
  ('progress-growth', 'What''s a pattern or habit you''re becoming more aware of?'),
  ('progress-growth', 'What''s something you''re learning to do differently in your recovery?'),
  ('progress-growth', 'What belief about yourself is beginning to shift?'),
  ('progress-growth', 'What''s a small victory you had this week, even if no one else noticed?'),
  ('progress-growth', 'What skill or coping tool are you getting better at using?'),
  ('progress-growth', 'How have you shown up for yourself differently lately?'),
  ('progress-growth', 'What''s becoming easier that used to feel impossible?'),
  ('progress-growth', 'What have you learned about your needs or boundaries recently?'),
  ('progress-growth', 'What''s a way you''ve surprised yourself in your healing journey?'),
  ('progress-growth', 'What old story about yourself are you starting to release?'),
  ('progress-growth', 'What''s something you''re proud of about your journey, without minimizing it?'),
  ('progress-growth', 'How has your relationship with yourself evolved?'),
  ('progress-growth', 'What''s a new perspective you''re beginning to embrace?'),
  ('progress-growth', 'What progress are you making that isn''t visible to others?'),
  ('coping-resilience', 'What helps you feel grounded when things feel chaotic?'),
  ('coping-resilience', 'What''s your go-to coping strategy, and is it serving you right now?'),
  ('coping-resilience', 'What do you need most when you''re struggling?'),
  ('coping-resilience', 'What helps you reconnect with yourself when you feel disconnected?'),
  ('coping-resilience', 'What''s a healthy way you''ve been managing difficult feelings?'),
  ('coping-resilience', 'Who can you reach out to when you need support, and what stops you from doing so?'),
  ('coping-resilience', 'What''s one thing you can do right now to take care of yourself?'),
  ('coping-resilience', 'What gives you strength to keep going on difficult days?'),
  ('coping-resilience', 'What does resilience look like for you?'),
  ('coping-resilience', 'What reminder or affirmation do you need to hear when things feel hard?'),
  ('coping-resilience', 'What safe space (physical or mental) can you retreat to when you need it?'),
  ('coping-resilience', 'What have you survived that shows your strength?'),
  ('coping-resilience', 'What soothes you when you''re feeling activated or triggered?'),
  ('coping-resilience', 'What''s a challenge you''re facing, and what resources do you have to help you through it?'),
  ('coping-resilience', 'What helps you feel safe in your body?'),
  ('coping-resilience', 'What do you wish others understood about what you''re going through?'),
  ('coping-resilience', 'What helps you return to the present moment when anxiety takes over?'),
  ('coping-resilience', 'What''s a boundary you''ve set that has protected your wellbeing?'),
  ('coping-resilience', 'What''s helping you move through this moment, even if it''s just one breath at a time?'),
  ('coping-resilience', 'What would support look like for you today?')
) AS v(category, prompt_text)
WHERE NOT EXISTS (SELECT 1 FROM prompts LIMIT 1);

-- ============================================================================
-- Insert affirmations (50 total)
-- ============================================================================
INSERT INTO affirmations (category, affirmation_text)
SELECT * FROM (VALUES
  ('unconditional_self_worth', 'Your worth is not determined by your appearance, your size, or what you eat.'),
  ('unconditional_self_worth', 'You are inherently worthy of love and respect, exactly as you are right now.'),
  ('unconditional_self_worth', 'You are more than what you see in the mirror.'),
  ('unconditional_self_worth', 'Your value as a person exists independent of your body.'),
  ('unconditional_self_worth', 'You don''t have to earn your place in this world.'),
  ('unconditional_self_worth', 'Your thoughts and feelings matter, regardless of your body.'),
  ('unconditional_self_worth', 'You are worthy of care and compassion simply because you exist.'),
  ('unconditional_self_worth', 'Your worth is not a reflection in the mirror—it lives in your heart.'),
  ('unconditional_self_worth', 'You are enough, without changing a single thing.'),
  ('unconditional_self_worth', 'Your humanity is not conditional on meeting any standard.'),
  ('unconditional_self_worth', 'You deserve to take up space in this world.'),
  ('unconditional_self_worth', 'Your contributions to the world go far beyond your appearance.'),
  ('unconditional_self_worth', 'You are not a ''before'' or ''after''—you are a whole person, always.'),
  ('unconditional_self_worth', 'Your worth cannot be measured or weighed.'),
  ('unconditional_self_worth', 'You are deserving of kindness, especially from yourself.'),
  ('recovery_is_non_linear', 'Recovery is not linear, and that''s completely okay.'),
  ('recovery_is_non_linear', 'Setbacks are part of the journey, not a sign of failure.'),
  ('recovery_is_non_linear', 'You don''t have to be perfect at recovery—progress matters more than perfection.'),
  ('recovery_is_non_linear', 'Having a hard day doesn''t erase your progress.'),
  ('recovery_is_non_linear', 'Recovery has ups and downs—both are valid parts of healing.'),
  ('recovery_is_non_linear', 'You''re allowed to take recovery one moment at a time.'),
  ('recovery_is_non_linear', 'Struggling doesn''t mean you''re moving backwards.'),
  ('recovery_is_non_linear', 'Some days will be harder than others, and that doesn''t define your journey.'),
  ('recovery_is_non_linear', 'Recovery doesn''t have a timeline—your pace is valid.'),
  ('recovery_is_non_linear', 'You don''t have to have it all figured out today.'),
  ('body_acceptance', 'Your body deserves kindness, not criticism.'),
  ('body_acceptance', 'Your body is working hard to keep you alive—it deserves respect.'),
  ('body_acceptance', 'You can honor your body without loving every part of it.'),
  ('body_acceptance', 'Your body is not the enemy—it''s been with you through everything.'),
  ('body_acceptance', 'Making peace with your body is a process, not a destination.'),
  ('body_acceptance', 'Your body''s worth is not determined by how it looks.'),
  ('body_acceptance', 'It''s okay to have complicated feelings about your body.'),
  ('body_acceptance', 'Your body carries you through life—that''s worth acknowledging.'),
  ('body_acceptance', 'You don''t owe anyone a certain body type or appearance.'),
  ('body_acceptance', 'Your body is the least interesting thing about you.'),
  ('nourishment_and_self_care', 'You deserve nourishment and care, unconditionally.'),
  ('nourishment_and_self_care', 'Taking care of yourself is not selfish—it''s necessary.'),
  ('nourishment_and_self_care', 'You are allowed to rest without earning it.'),
  ('nourishment_and_self_care', 'Listening to your body''s needs is an act of self-respect.'),
  ('nourishment_and_self_care', 'Self-care looks different every day, and that''s okay.'),
  ('nourishment_and_self_care', 'You deserve comfort and gentleness, especially on hard days.'),
  ('nourishment_and_self_care', 'Meeting your needs is not weakness—it''s wisdom.'),
  ('nourishment_and_self_care', 'You''re allowed to prioritize your wellbeing.'),
  ('nourishment_and_self_care', 'Caring for yourself is a radical act in a world that tells you not to.'),
  ('nourishment_and_self_care', 'You deserve to feel safe and cared for in your own life.'),
  ('strength_and_resilience', 'Every day you choose recovery is a victory, no matter how small it feels.'),
  ('strength_and_resilience', 'It''s okay to struggle—recovery is hard work.'),
  ('strength_and_resilience', 'You are stronger than you realize, even on days when you feel weak.'),
  ('strength_and_resilience', 'Choosing to keep going, even when it''s hard, is an act of courage.'),
  ('strength_and_resilience', 'You''ve survived every difficult day so far—that''s proof of your strength.')
) AS v(category, affirmation_text)
WHERE NOT EXISTS (SELECT 1 FROM affirmations LIMIT 1);

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Summary:
--   - 100 prompts inserted
--   - 50 affirmations inserted
--
-- Next steps:
--   1. Run: supabase db push
--   2. Verify data in Supabase Studio
--   3. Test prompt/affirmation fetching in app
-- ============================================================================
